language: node_js
node_js:
- '6'
env:
  matrix:
  - TRAVIS_NODE_VERSION="6.3"
before_script:
- webpack
install:
- npm install
cache:
  directories:
  - node_modules
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAILFVX7VJZDRQK3IQ
  secret_access_key:
    secure: C/IsNXyAq1IecVgKOuVb+lfVsEo8s3buW/Izi0hwljls9xv7MQ4nob6rcP96NV2kFaTFSUu/QvHqb/Sp29sMybw7TjI0cdERtxZ7Sm1BsvuLdKZ9ieAJsurdR7oLMrv3fZ9pSTdAIvLOggiTMkT+/ONEpq6zyK+IeOIcEdzmAc0Kx60Qvl0dRy/WbHIOR+pnL6pGgBY4kmkai3gVqec5NKdp4LHWjdhrg8VizH77r5Ws/80OPcgGRMGQZgPVMLVBaXgfBOImpki7uZDd8LJvOTDFTLTCEii7DJ0nbrLIhju/dU3avYIkuSWPRd+YWbBESbQTslg/SUKW6uEpQ90T6c681cf+EyiLAqbi+zWRH8/d+WvXjOm11VXqg2+UTvdJZeyO14AV8HmPYuITPaOLLwW6DmUSQMZmm24RxlJF28qKDdeaohUlcYx/SWR0qk/Fe0kq0Io0gowX/cCYxQ0wxvKasOFzQUVBMr9iuyoV3cLerrczz93T0zKwdffVPQsellpbAiKhHtP1myBrgJZVdwuf/4pmpUfbDVh55I8THgaCp6G3+ctgmaWVslDF5sRYxcfXwgcDTz8Vi1AmPyL5NrbE6SQ93AqA+lrDpsdMTtetRNQzx2GTDRAx7n7U27wMtBHb21W7b5sMVKkKSOkfJe+tdClj6EG0CKFeKFOwI5s=
  region: us-east-2
  app: flickpick
  env: fliq
  bucket_name: elasticbeanstalk-us-east-2-088432678416
  on:
    repo: binary100/flick-pick
    branch: dev
